version: '3.8'
services:
  postgres:
    image: 'd57ed788c154'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: louis-vuitton
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./louis-vuitton-api
    ports:
      - '80:80'
    # env_file:
    #   - ./env/backend.env
    #   - ./louis-vuitton-api/.env
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: louis-vuitton
  frontend:
    build: ./luis-vuitton
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data:
